services:
  db:
    image: postgres:15
    container_name: foliage-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foliage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: foliage-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=host=db user=postgres password=postgres dbname=foliage port=5432 sslmode=disable
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

volumes:
  postgres_data: